SELECT
        t1.dtRef,
        t1.idCliente,
        t1.idadeDias,
        t1.qtdeAtivacaoVida,
        t1.qtdeAtivacaoD7,
        t1.qtdeAtivacaoD14, 
        t1.qtdeAtivacaoD28,
        t1.qtdeAtivacaoD56,
        t1.qtdeTransacaoVida,
        t1.qtdeTransacaoD7,
        t1.qtdeTransacaoD14,
        t1.qtdeTransacaoD28,
        t1.qtdeTransacaoD56,
        t1.saldoVida,
        t1.SaldoD7,
        t1.SaldoD14,
        t1.SaldoD28,
        t1.SaldoD56,
        t1.qtdePontosPosVida,
        t1.qtdePontosPosD7,
        t1.qtdePontosPosD14,
        t1.qtdePontosPosD28,
        t1.qtdePontosPosD56,
        t1.qtdePontosNegVida,
        t1.qtdePontosNegD7,
        t1.qtdePontosNegD14,
        t1.qtdePontosNegD28,
        t1.qtdePontosNegD56,
        t1.qtdeTransaocaoManha,
        t1.qtdeTransaocaoTarde,
        t1.qtdeTransaocaoNoite,
        t1.pctTransaocaoManha,
        t1.pctTransaocaoTarde,
        t1.pctTransaocaoNoite,
        t1.QtdeTransacaoDiaVida, 
        t1.QtdeTransacaoDiaD7,
        t1.QtdeTransacaoDiaD14,
        t1.QtdeTransacaoDiaD28,
        t1.QtdeTransacaoDiaD56,
        t1.pctAtivacaoMAU,
        t1.qtdeHorasVida,
        t1.qtdeHorasD7,
        t1.qtdeHorasD14,
        t1.qtdeHorasD28,
        t1.qtdeHorasD56,
        t1.avgIntervaloDiasVida,
        t1.avgIntervaloDiasD28,
        t1.qtdeChatMessage,
        t1.qtdeAirflowLover,
        t1.qtdeRLover,
        t1.qtdeResgatarPonei,
        t1.qtdeListadePresenca,
        t1.qtdePresencaStreak,
        t1.qtdeTrocadePontosStreamElements,
        t1.qtdeReembolsoTrocadePontosStreamElements,
        t1.qtdeAdaga,
        t1.qtdeAarmadura,
        t1.qtdeBotas,
        t1.qtdeCajado,
        t1.qtdeChapeu,
        t1.qtdeChurn_model,
        t1.qtdeEspada,
        t1.qtdeRPG,
        t2.qtdeFrequencia,
        t2.descLifeCycleAtual,
        t2.descLifeCycleD28,
        t2.pctZUMBI,
        t2.pctDESENCANTADA,
        t2.pctCURIOSO,
        t2.pctFIEL,
        t2.pctRECONQUISTADO,
        t2.pctTURISTA,
        t2.pctREBORN,
        t2.avgFreqGrupo,
        t2.ratioFreqGrupo,
        t3.qtdeCursosCompletos,
        t3.qtdeCursosIncompletos,
        t3.carreira,
        t3.coletadados2024,
        t3.dsdatabricks2024,
        t3.dspontos2024,
        t3.estatistica2024,
        t3.estatistica2025,
        t3.github2024,
        t3.github2025,
        t3.go2026,
        t3.iacanal2025,
        t3.lagomago2024,
        t3.loyaltypredict2025,
        t3.machinelearning2025,
        t3.matchmakingtrampardecasa2024,
        t3.ml2024,
        t3.mlflow2025,
        t3.nekt2025,
        t3.pandas2024,
        t3.pandas2025,
        t3.python2024,
        t3.python2025,
        t3.speedf1,
        t3.sql2020,
        t3.sql2025,
        t3.streamlit2025,
        t3.tramparlakehouse2024,
        t3.tseanalytics2024,
        t3.qtdDiasUltAtividade

FROM fs_transacional AS t1

LEFT JOIN fs_life_cycle AS t2
ON t1.IdCliente = t2.IdCliente
AND t1.dtRef = t2.dtRef

LEFT JOIN fs_education AS t3
ON t1.IdCliente = t3.IdCliente
AND t1.dtRef = t3.dtRef

WHERE t1.dtRef = (SELECT MAX(dtRef) FROM fs_transacional)